apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "speedle.fullname" . }}
  labels:
    app: speedle
    chart: {{ template "speedle.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: speedle
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: speedle
        release: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "speedle.fullname" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      imagePullSecrets:
        - name: "{{ .Values.image.pullSecret }}"
      containers:
        - name: pms
          image: "{{ .Values.image.pms }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/speedle
              name: policy-store
          ports:
            - name: pms
              containerPort: 6733
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 6733
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 6733
            initialDelaySeconds: 5
            periodSeconds: 5
        - name: ads
          image: "{{ .Values.image.ads }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: /var/lib/speedle
              name: policy-store
          ports:
            - name: ads
              containerPort: 6734
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /health
              port: 6734
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 6734
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
      - name: policy-store
        hostPath:
          path: /home/opc/policystore
