// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Principal
	Subject
	ContextRequest
	IsAllowedResponse
	AndPrincipals
	RolePolicy
	Policy
	EvaluatedCondition
	EvaluatedRolePolicy
	EvaluatedPolicy
	EvaluationDebugResponse
	AllRoleResponse
	AllPermissionResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Principal struct {
	Type string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Idd  string `protobuf:"bytes,3,opt,name=idd" json:"idd,omitempty"`
}

func (m *Principal) Reset()                    { *m = Principal{} }
func (m *Principal) String() string            { return proto.CompactTextString(m) }
func (*Principal) ProtoMessage()               {}
func (*Principal) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Principal) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Principal) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Principal) GetIdd() string {
	if m != nil {
		return m.Idd
	}
	return ""
}

type Subject struct {
	Principals []*Principal `protobuf:"bytes,1,rep,name=principals" json:"principals,omitempty"`
	TokenType  string       `protobuf:"bytes,2,opt,name=tokenType" json:"tokenType,omitempty"`
	Token      string       `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *Subject) Reset()                    { *m = Subject{} }
func (m *Subject) String() string            { return proto.CompactTextString(m) }
func (*Subject) ProtoMessage()               {}
func (*Subject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Subject) GetPrincipals() []*Principal {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *Subject) GetTokenType() string {
	if m != nil {
		return m.TokenType
	}
	return ""
}

func (m *Subject) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ContextRequest struct {
	Subject     *Subject          `protobuf:"bytes,1,opt,name=subject" json:"subject,omitempty"`
	ServiceName string            `protobuf:"bytes,2,opt,name=serviceName" json:"serviceName,omitempty"`
	Resource    string            `protobuf:"bytes,3,opt,name=resource" json:"resource,omitempty"`
	Action      string            `protobuf:"bytes,4,opt,name=action" json:"action,omitempty"`
	Attributes  map[string]string `protobuf:"bytes,5,rep,name=attributes" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ContextRequest) Reset()                    { *m = ContextRequest{} }
func (m *ContextRequest) String() string            { return proto.CompactTextString(m) }
func (*ContextRequest) ProtoMessage()               {}
func (*ContextRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ContextRequest) GetSubject() *Subject {
	if m != nil {
		return m.Subject
	}
	return nil
}

func (m *ContextRequest) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ContextRequest) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *ContextRequest) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *ContextRequest) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type IsAllowedResponse struct {
	Allowed bool   `protobuf:"varint,1,opt,name=allowed" json:"allowed,omitempty"`
	Reason  int32  `protobuf:"varint,2,opt,name=reason" json:"reason,omitempty"`
	ErrMsg  string `protobuf:"bytes,3,opt,name=errMsg" json:"errMsg,omitempty"`
}

func (m *IsAllowedResponse) Reset()                    { *m = IsAllowedResponse{} }
func (m *IsAllowedResponse) String() string            { return proto.CompactTextString(m) }
func (*IsAllowedResponse) ProtoMessage()               {}
func (*IsAllowedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *IsAllowedResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *IsAllowedResponse) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

func (m *IsAllowedResponse) GetErrMsg() string {
	if m != nil {
		return m.ErrMsg
	}
	return ""
}

type AndPrincipals struct {
	Principals []string `protobuf:"bytes,1,rep,name=principals" json:"principals,omitempty"`
}

func (m *AndPrincipals) Reset()                    { *m = AndPrincipals{} }
func (m *AndPrincipals) String() string            { return proto.CompactTextString(m) }
func (*AndPrincipals) ProtoMessage()               {}
func (*AndPrincipals) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AndPrincipals) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

type RolePolicy struct {
	ID                  string   `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name                string   `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Effect              string   `protobuf:"bytes,3,opt,name=Effect" json:"Effect,omitempty"`
	Roles               []string `protobuf:"bytes,4,rep,name=Roles" json:"Roles,omitempty"`
	Principals          []string `protobuf:"bytes,5,rep,name=Principals" json:"Principals,omitempty"`
	Resources           []string `protobuf:"bytes,6,rep,name=Resources" json:"Resources,omitempty"`
	ResourceExpressions []string `protobuf:"bytes,7,rep,name=ResourceExpressions" json:"ResourceExpressions,omitempty"`
	Condition           string   `protobuf:"bytes,8,opt,name=Condition" json:"Condition,omitempty"`
}

func (m *RolePolicy) Reset()                    { *m = RolePolicy{} }
func (m *RolePolicy) String() string            { return proto.CompactTextString(m) }
func (*RolePolicy) ProtoMessage()               {}
func (*RolePolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *RolePolicy) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *RolePolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *RolePolicy) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *RolePolicy) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *RolePolicy) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *RolePolicy) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *RolePolicy) GetResourceExpressions() []string {
	if m != nil {
		return m.ResourceExpressions
	}
	return nil
}

func (m *RolePolicy) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type Policy struct {
	ID          string               `protobuf:"bytes,1,opt,name=ID" json:"ID,omitempty"`
	Name        string               `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Effect      string               `protobuf:"bytes,3,opt,name=Effect" json:"Effect,omitempty"`
	Permissions []*Policy_Permission `protobuf:"bytes,4,rep,name=permissions" json:"permissions,omitempty"`
	Principals  []*AndPrincipals     `protobuf:"bytes,5,rep,name=Principals" json:"Principals,omitempty"`
	Condition   string               `protobuf:"bytes,6,opt,name=Condition" json:"Condition,omitempty"`
}

func (m *Policy) Reset()                    { *m = Policy{} }
func (m *Policy) String() string            { return proto.CompactTextString(m) }
func (*Policy) ProtoMessage()               {}
func (*Policy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Policy) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Policy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Policy) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *Policy) GetPermissions() []*Policy_Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *Policy) GetPrincipals() []*AndPrincipals {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *Policy) GetCondition() string {
	if m != nil {
		return m.Condition
	}
	return ""
}

type Policy_Permission struct {
	Resource           string   `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	ResourceExpression string   `protobuf:"bytes,2,opt,name=resourceExpression" json:"resourceExpression,omitempty"`
	Actions            []string `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
}

func (m *Policy_Permission) Reset()                    { *m = Policy_Permission{} }
func (m *Policy_Permission) String() string            { return proto.CompactTextString(m) }
func (*Policy_Permission) ProtoMessage()               {}
func (*Policy_Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6, 0} }

func (m *Policy_Permission) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *Policy_Permission) GetResourceExpression() string {
	if m != nil {
		return m.ResourceExpression
	}
	return ""
}

func (m *Policy_Permission) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type EvaluatedCondition struct {
	ConditionExpression string `protobuf:"bytes,1,opt,name=ConditionExpression" json:"ConditionExpression,omitempty"`
	EvaluationResult    string `protobuf:"bytes,2,opt,name=EvaluationResult" json:"EvaluationResult,omitempty"`
}

func (m *EvaluatedCondition) Reset()                    { *m = EvaluatedCondition{} }
func (m *EvaluatedCondition) String() string            { return proto.CompactTextString(m) }
func (*EvaluatedCondition) ProtoMessage()               {}
func (*EvaluatedCondition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *EvaluatedCondition) GetConditionExpression() string {
	if m != nil {
		return m.ConditionExpression
	}
	return ""
}

func (m *EvaluatedCondition) GetEvaluationResult() string {
	if m != nil {
		return m.EvaluationResult
	}
	return ""
}

type EvaluatedRolePolicy struct {
	Status              string              `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	ID                  string              `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
	Name                string              `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Effect              string              `protobuf:"bytes,4,opt,name=Effect" json:"Effect,omitempty"`
	Roles               []string            `protobuf:"bytes,5,rep,name=Roles" json:"Roles,omitempty"`
	Principals          []string            `protobuf:"bytes,6,rep,name=Principals" json:"Principals,omitempty"`
	Resources           []string            `protobuf:"bytes,7,rep,name=Resources" json:"Resources,omitempty"`
	ResourceExpressions []string            `protobuf:"bytes,8,rep,name=ResourceExpressions" json:"ResourceExpressions,omitempty"`
	Condition           *EvaluatedCondition `protobuf:"bytes,9,opt,name=Condition" json:"Condition,omitempty"`
}

func (m *EvaluatedRolePolicy) Reset()                    { *m = EvaluatedRolePolicy{} }
func (m *EvaluatedRolePolicy) String() string            { return proto.CompactTextString(m) }
func (*EvaluatedRolePolicy) ProtoMessage()               {}
func (*EvaluatedRolePolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *EvaluatedRolePolicy) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EvaluatedRolePolicy) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EvaluatedRolePolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EvaluatedRolePolicy) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *EvaluatedRolePolicy) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *EvaluatedRolePolicy) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *EvaluatedRolePolicy) GetResources() []string {
	if m != nil {
		return m.Resources
	}
	return nil
}

func (m *EvaluatedRolePolicy) GetResourceExpressions() []string {
	if m != nil {
		return m.ResourceExpressions
	}
	return nil
}

func (m *EvaluatedRolePolicy) GetCondition() *EvaluatedCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type EvaluatedPolicy struct {
	Status      string                        `protobuf:"bytes,1,opt,name=Status" json:"Status,omitempty"`
	ID          string                        `protobuf:"bytes,2,opt,name=ID" json:"ID,omitempty"`
	Name        string                        `protobuf:"bytes,3,opt,name=Name" json:"Name,omitempty"`
	Effect      string                        `protobuf:"bytes,4,opt,name=Effect" json:"Effect,omitempty"`
	Permissions []*EvaluatedPolicy_Permission `protobuf:"bytes,5,rep,name=permissions" json:"permissions,omitempty"`
	Principals  []string                      `protobuf:"bytes,6,rep,name=Principals" json:"Principals,omitempty"`
	Condition   *EvaluatedCondition           `protobuf:"bytes,7,opt,name=Condition" json:"Condition,omitempty"`
}

func (m *EvaluatedPolicy) Reset()                    { *m = EvaluatedPolicy{} }
func (m *EvaluatedPolicy) String() string            { return proto.CompactTextString(m) }
func (*EvaluatedPolicy) ProtoMessage()               {}
func (*EvaluatedPolicy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *EvaluatedPolicy) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *EvaluatedPolicy) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *EvaluatedPolicy) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *EvaluatedPolicy) GetEffect() string {
	if m != nil {
		return m.Effect
	}
	return ""
}

func (m *EvaluatedPolicy) GetPermissions() []*EvaluatedPolicy_Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

func (m *EvaluatedPolicy) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *EvaluatedPolicy) GetCondition() *EvaluatedCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

type EvaluatedPolicy_Permission struct {
	Resource           string   `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	ResourceExpression string   `protobuf:"bytes,2,opt,name=resourceExpression" json:"resourceExpression,omitempty"`
	Actions            []string `protobuf:"bytes,3,rep,name=actions" json:"actions,omitempty"`
}

func (m *EvaluatedPolicy_Permission) Reset()                    { *m = EvaluatedPolicy_Permission{} }
func (m *EvaluatedPolicy_Permission) String() string            { return proto.CompactTextString(m) }
func (*EvaluatedPolicy_Permission) ProtoMessage()               {}
func (*EvaluatedPolicy_Permission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9, 0} }

func (m *EvaluatedPolicy_Permission) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *EvaluatedPolicy_Permission) GetResourceExpression() string {
	if m != nil {
		return m.ResourceExpression
	}
	return ""
}

func (m *EvaluatedPolicy_Permission) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

type EvaluationDebugResponse struct {
	Allowed        bool                   `protobuf:"varint,1,opt,name=allowed" json:"allowed,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason" json:"reason,omitempty"`
	RequestContext *ContextRequest        `protobuf:"bytes,3,opt,name=requestContext" json:"requestContext,omitempty"`
	GrantedRoles   []string               `protobuf:"bytes,4,rep,name=grantedRoles" json:"grantedRoles,omitempty"`
	RolePolicies   []*EvaluatedRolePolicy `protobuf:"bytes,5,rep,name=rolePolicies" json:"rolePolicies,omitempty"`
	Policies       []*EvaluatedPolicy     `protobuf:"bytes,6,rep,name=policies" json:"policies,omitempty"`
}

func (m *EvaluationDebugResponse) Reset()                    { *m = EvaluationDebugResponse{} }
func (m *EvaluationDebugResponse) String() string            { return proto.CompactTextString(m) }
func (*EvaluationDebugResponse) ProtoMessage()               {}
func (*EvaluationDebugResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *EvaluationDebugResponse) GetAllowed() bool {
	if m != nil {
		return m.Allowed
	}
	return false
}

func (m *EvaluationDebugResponse) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *EvaluationDebugResponse) GetRequestContext() *ContextRequest {
	if m != nil {
		return m.RequestContext
	}
	return nil
}

func (m *EvaluationDebugResponse) GetGrantedRoles() []string {
	if m != nil {
		return m.GrantedRoles
	}
	return nil
}

func (m *EvaluationDebugResponse) GetRolePolicies() []*EvaluatedRolePolicy {
	if m != nil {
		return m.RolePolicies
	}
	return nil
}

func (m *EvaluationDebugResponse) GetPolicies() []*EvaluatedPolicy {
	if m != nil {
		return m.Policies
	}
	return nil
}

type AllRoleResponse struct {
	Roles []string `protobuf:"bytes,1,rep,name=roles" json:"roles,omitempty"`
}

func (m *AllRoleResponse) Reset()                    { *m = AllRoleResponse{} }
func (m *AllRoleResponse) String() string            { return proto.CompactTextString(m) }
func (*AllRoleResponse) ProtoMessage()               {}
func (*AllRoleResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *AllRoleResponse) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type AllPermissionResponse struct {
	Permissions []*AllPermissionResponse_Permission `protobuf:"bytes,1,rep,name=permissions" json:"permissions,omitempty"`
}

func (m *AllPermissionResponse) Reset()                    { *m = AllPermissionResponse{} }
func (m *AllPermissionResponse) String() string            { return proto.CompactTextString(m) }
func (*AllPermissionResponse) ProtoMessage()               {}
func (*AllPermissionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *AllPermissionResponse) GetPermissions() []*AllPermissionResponse_Permission {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type AllPermissionResponse_Permission struct {
	Resource string   `protobuf:"bytes,1,opt,name=resource" json:"resource,omitempty"`
	Actions  []string `protobuf:"bytes,2,rep,name=actions" json:"actions,omitempty"`
}

func (m *AllPermissionResponse_Permission) Reset()         { *m = AllPermissionResponse_Permission{} }
func (m *AllPermissionResponse_Permission) String() string { return proto.CompactTextString(m) }
func (*AllPermissionResponse_Permission) ProtoMessage()    {}
func (*AllPermissionResponse_Permission) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12, 0}
}

func (m *AllPermissionResponse_Permission) GetResource() string {
	if m != nil {
		return m.Resource
	}
	return ""
}

func (m *AllPermissionResponse_Permission) GetActions() []string {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*Principal)(nil), "ads_pb.Principal")
	proto.RegisterType((*Subject)(nil), "ads_pb.Subject")
	proto.RegisterType((*ContextRequest)(nil), "ads_pb.ContextRequest")
	proto.RegisterType((*IsAllowedResponse)(nil), "ads_pb.IsAllowedResponse")
	proto.RegisterType((*AndPrincipals)(nil), "ads_pb.AndPrincipals")
	proto.RegisterType((*RolePolicy)(nil), "ads_pb.RolePolicy")
	proto.RegisterType((*Policy)(nil), "ads_pb.Policy")
	proto.RegisterType((*Policy_Permission)(nil), "ads_pb.Policy.Permission")
	proto.RegisterType((*EvaluatedCondition)(nil), "ads_pb.EvaluatedCondition")
	proto.RegisterType((*EvaluatedRolePolicy)(nil), "ads_pb.EvaluatedRolePolicy")
	proto.RegisterType((*EvaluatedPolicy)(nil), "ads_pb.EvaluatedPolicy")
	proto.RegisterType((*EvaluatedPolicy_Permission)(nil), "ads_pb.EvaluatedPolicy.Permission")
	proto.RegisterType((*EvaluationDebugResponse)(nil), "ads_pb.EvaluationDebugResponse")
	proto.RegisterType((*AllRoleResponse)(nil), "ads_pb.AllRoleResponse")
	proto.RegisterType((*AllPermissionResponse)(nil), "ads_pb.AllPermissionResponse")
	proto.RegisterType((*AllPermissionResponse_Permission)(nil), "ads_pb.AllPermissionResponse.Permission")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Evaluator service

type EvaluatorClient interface {
	IsAllowed(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error)
	GetAllGrantedRoles(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*AllRoleResponse, error)
	GetAllPermissions(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*AllPermissionResponse, error)
	Discover(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error)
	Diagnose(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*EvaluationDebugResponse, error)
}

type evaluatorClient struct {
	cc *grpc.ClientConn
}

func NewEvaluatorClient(cc *grpc.ClientConn) EvaluatorClient {
	return &evaluatorClient{cc}
}

func (c *evaluatorClient) IsAllowed(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error) {
	out := new(IsAllowedResponse)
	err := grpc.Invoke(ctx, "/pb.Evaluator/IsAllowed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaluatorClient) GetAllGrantedRoles(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*AllRoleResponse, error) {
	out := new(AllRoleResponse)
	err := grpc.Invoke(ctx, "/pb.Evaluator/GetAllGrantedRoles", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaluatorClient) GetAllPermissions(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*AllPermissionResponse, error) {
	out := new(AllPermissionResponse)
	err := grpc.Invoke(ctx, "/pb.Evaluator/GetAllPermissions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaluatorClient) Discover(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*IsAllowedResponse, error) {
	out := new(IsAllowedResponse)
	err := grpc.Invoke(ctx, "/pb.Evaluator/Discover", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *evaluatorClient) Diagnose(ctx context.Context, in *ContextRequest, opts ...grpc.CallOption) (*EvaluationDebugResponse, error) {
	out := new(EvaluationDebugResponse)
	err := grpc.Invoke(ctx, "/pb.Evaluator/Diagnose", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Evaluator service

type EvaluatorServer interface {
	IsAllowed(context.Context, *ContextRequest) (*IsAllowedResponse, error)
	GetAllGrantedRoles(context.Context, *ContextRequest) (*AllRoleResponse, error)
	GetAllPermissions(context.Context, *ContextRequest) (*AllPermissionResponse, error)
	Discover(context.Context, *ContextRequest) (*IsAllowedResponse, error)
	Diagnose(context.Context, *ContextRequest) (*EvaluationDebugResponse, error)
}

func RegisterEvaluatorServer(s *grpc.Server, srv EvaluatorServer) {
	s.RegisterService(&_Evaluator_serviceDesc, srv)
}

func _Evaluator_IsAllowed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorServer).IsAllowed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Evaluator/IsAllowed",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorServer).IsAllowed(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evaluator_GetAllGrantedRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorServer).GetAllGrantedRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Evaluator/GetAllGrantedRoles",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorServer).GetAllGrantedRoles(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evaluator_GetAllPermissions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorServer).GetAllPermissions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Evaluator/GetAllPermissions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorServer).GetAllPermissions(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evaluator_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Evaluator/Discover",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorServer).Discover(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Evaluator_Diagnose_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EvaluatorServer).Diagnose(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Evaluator/Diagnose",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EvaluatorServer).Diagnose(ctx, req.(*ContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Evaluator_serviceDesc = grpc.ServiceDesc{
	ServiceName: "ads_pb.Evaluator",
	HandlerType: (*EvaluatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IsAllowed",
			Handler:    _Evaluator_IsAllowed_Handler,
		},
		{
			MethodName: "GetAllGrantedRoles",
			Handler:    _Evaluator_GetAllGrantedRoles_Handler,
		},
		{
			MethodName: "GetAllPermissions",
			Handler:    _Evaluator_GetAllPermissions_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _Evaluator_Discover_Handler,
		},
		{
			MethodName: "Diagnose",
			Handler:    _Evaluator_Diagnose_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("ads_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xc4, 0x56, 0xdd, 0x8e, 0xdb, 0x44, 
	0x14, 0x4e, 0x9c, 0xc4, 0x89, 0x4f, 0xda, 0xdd, 0x66, 0xd2, 0x6e, 0x4d, 0x40, 0xd5, 0x6a, 0x04, 
	0xa2, 0x42, 0x22, 0x85, 0x80, 0xd4, 0xaa, 0xa8, 0x82, 0xb4, 0x09, 0xd5, 0x5e, 0x80, 0x22, 0x97, 
	0x5b, 0x84, 0x9c, 0x64, 0x1a, 0x99, 0xba, 0x1e, 0x33, 0x33, 0x5e, 0x9a, 0xb7, 0xe0, 0x96, 0x6b, 
	0xc4, 0x8b, 0x20, 0x1e, 0x87, 0x1b, 0xde, 0x00, 0xcd, 0x8f, 0xed, 0x71, 0xec, 0xd0, 0xad, 0x04, 
	0xea, 0x9d, 0xcf, 0x99, 0x33, 0xe7, 0xef, 0xfb, 0xce, 0x1c, 0xc3, 0x28, 0xdc, 0xf2, 0x1f, 0x38, 
	0x61, 0x97, 0xd1, 0x86, 0x4c, 0x53, 0x46, 0x05, 0x45, 0xae, 0x54, 0xa5, 0x6b, 0xbc, 0x04, 0x6f, 
	0xc5, 0xa2, 0x64, 0x13, 0xa5, 0x61, 0x8c, 0x10, 0x74, 0xc5, 0x3e, 0x25, 0x7e, 0xfb, 0xbc, 0x7d, 
	0xd7, 0x0b, 0xd4, 0xb7, 0xd4, 0x25, 0xe1, 0x4b, 0xe2, 0x3b, 0x5a, 0x27, 0xbf, 0xd1, 0x0d, 0xe8, 
	0x44, 0xdb, 0xad, 0xdf, 0x51, 0x2a, 0xf9, 0x89, 0x63, 0xe8, 0x3f, 0xcb, 0xd6, 0x3f, 0x92, 0x8d, 
	0x40, 0x1f, 0x03, 0xa4, 0xb9, 0x47, 0xee, 0xb7, 0xcf, 0x3b, 0x77, 0x87, 0xb3, 0xeb, 0xd3, 0x74, 
	0x3d, 0x2d, 0xe2, 0x04, 0x96, 0x01, 0x7a, 0x0f, 0x3c, 0x41, 0x5f, 0x90, 0xe4, 0x3b, 0x19, 0x58, 
	0x07, 0x29, 0x15, 0xe8, 0x26, 0xf4, 0x94, 0x60, 0x62, 0x69, 0x01, 0xff, 0xe2, 0xc0, 0xc9, 0x13, 
	0x9a, 0x08, 0xf2, 0x4a, 0x04, 0xe4, 0xa7, 0x8c, 0x70, 0x81, 0x3e, 0x80, 0x3e, 0xd7, 0x09, 0xa8, 
	0xec, 0x87, 0xb3, 0xa1, 0x0c, 0x69, 0x72, 0x0a, 0xf2, 0x33, 0x74, 0x0e, 0x43, 0xd3, 0x87, 0x6f, 
	0xcb, 0xa2, 0x6c, 0x15, 0x9a, 0xc0, 0x80, 0x11, 0x4e, 0x33, 0xb6, 0x21, 0x26, 0x68, 0x21, 0xa3, 
	0x33, 0x70, 0xc3, 0x8d, 0x88, 0x68, 0xe2, 0x77, 0xd5, 0x89, 0x91, 0xd0, 0x63, 0x80, 0x50, 0x08, 
	0x16, 0xad, 0x33, 0x41, 0xb8, 0xdf, 0x53, 0x25, 0x63, 0x19, 0xbf, 0x9a, 0xe4, 0x74, 0x5e, 0x18, 
	0x2d, 0x13, 0xc1, 0xf6, 0x81, 0x75, 0x6b, 0xf2, 0x08, 0x4e, 0x0f, 0x8e, 0x65, 0x9b, 0x5f, 0x90, 
	0xbd, 0x41, 0x43, 0x7e, 0xca, 0x76, 0x5c, 0x86, 0x71, 0x96, 0x27, 0xae, 0x85, 0x87, 0xce, 0x83, 
	0x36, 0xfe, 0x1e, 0x46, 0x17, 0x7c, 0x1e, 0xc7, 0xf4, 0x67, 0xb2, 0x0d, 0x08, 0x4f, 0x69, 0xc2, 
	0x09, 0xf2, 0xa1, 0x1f, 0x6a, 0x95, 0x72, 0x32, 0x08, 0x72, 0x51, 0x56, 0xc2, 0x48, 0xc8, 0x69, 
	0xa2, 0x3c, 0xf5, 0x02, 0x23, 0x49, 0x3d, 0x61, 0xec, 0x1b, 0xbe, 0x33, 0xb5, 0x1b, 0x09, 0xdf, 
	0x83, 0xeb, 0xf3, 0x64, 0xbb, 0x2a, 0x61, 0xbb, 0x53, 0x43, 0xd9, 0xb3, 0x61, 0xc5, 0x7f, 0xb5, 
	0x01, 0x02, 0x1a, 0x93, 0x15, 0x8d, 0xa3, 0xcd, 0x1e, 0x9d, 0x80, 0x73, 0xb1, 0x30, 0x95, 0x38, 
	0x17, 0x0b, 0xc9, 0x2a, 0x0b, 0x00, 0xf5, 0x2d, 0x63, 0x2f, 0x9f, 0x3f, 0x97, 0x08, 0x9a, 0xd8, 
	0x5a, 0x92, 0x45, 0x4b, 0x4f, 0xdc, 0xef, 0xaa, 0x28, 0x5a, 0x90, 0x09, 0x94, 0xe9, 0xa8, 0x9e, 
	0x7b, 0x81, 0xa5, 0x91, 0xbc, 0x0a, 0x0c, 0x6e, 0xdc, 0x77, 0xd5, 0x71, 0xa9, 0x40, 0x9f, 0xc0, 
	0x38, 0x17, 0x96, 0xaf, 0x52, 0x46, 0x38, 0x8f, 0x68, 0xc2, 0xfd, 0xbe, 0xb2, 0x6b, 0x3a, 0x92, 
	0xfe, 0x9e, 0xd0, 0x64, 0x1b, 0x29, 0xf8, 0x07, 0x9a, 0xa7, 0x85, 0x02, 0xff, 0xe1, 0x80, 0xfb, 
	0x1f, 0x94, 0x7a, 0x1f, 0x86, 0x29, 0x61, 0x2f, 0x23, 0x93, 0x4e, 0x57, 0x31, 0xe9, 0x96, 0x1a, 
	0x1e, 0xe5, 0x7c, 0xba, 0x2a, 0x4e, 0x03, 0xdb, 0x12, 0x7d, 0x5a, 0xeb, 0xc6, 0x70, 0x36, 0x92, 
	0xf7, 0x2a, 0xa8, 0x1d, 0x36, 0xa8, 0x2c, 0xc8, 0x3d, 0x28, 0x68, 0xc2, 0x00, 0xca, 0x58, 0x95, 
	0xa1, 0x68, 0x1f, 0x0c, 0xc5, 0x14, 0x10, 0xab, 0xf5, 0xcb, 0x54, 0xdb, 0x70, 0xa2, 0x48, 0xa9, 
	0xc6, 0x86, 0xfb, 0x1d, 0xd5, 0xee, 0x5c, 0xc4, 0x0c, 0xd0, 0x52, 0x32, 0x3a, 0x14, 0x64, 0x5b, 
	0x64, 0x22, 0xa1, 0x2a, 0x04, 0x2b, 0x80, 0x4e, 0xa3, 0xe9, 0x08, 0x7d, 0x04, 0x37, 0x8c, 0x1f, 
	0xd9, 0x27, 0xc2, 0xb3, 0x58, 0x98, 0x7c, 0x6a, 0x7a, 0xfc, 0xbb, 0x03, 0xe3, 0x22, 0xa8, 0x45, 
	0xd8, 0x33, 0x70, 0x9f, 0x89, 0x50, 0x64, 0xdc, 0x04, 0x32, 0x92, 0x41, 0xd7, 0xa9, 0xa1, 0xdb, 
	0x69, 0x44, 0xb7, 0xdb, 0x4c, 0xe4, 0xde, 0x71, 0x22, 0xbb, 0xff, 0x4e, 0xe4, 0xfe, 0x15, 0x89, 
	0x3c, 0x38, 0x4e, 0xe4, 0xcf, 0x6d, 0xdc, 0x3d, 0xf5, 0x56, 0x9e, 0x49, 0xa6, 0xd4, 0x5b, 0x6f, 
	0x13, 0xfc, 0x6f, 0x07, 0x4e, 0x0b, 0x8b, 0xff, 0xb1, 0x47, 0x5f, 0x55, 0x27, 0x40, 0x33, 0xf9, 
	0x4e, 0x25, 0xbf, 0xd7, 0x8c, 0xc2, 0xeb, 0xfa, 0x59, 0xa9, 0xbf, 0x7f, 0xc5, 0xfa, 0xdf, 0xca, 
	0x3c, 0xfc, 0xea, 0xc0, 0xed, 0x92, 0xb0, 0x0b, 0xb2, 0xce, 0x76, 0x6f, 0xfc, 0xb4, 0x7b, 0xc5, 
	0xd3, 0xfe, 0x10, 0x4e, 0x98, 0xde, 0x43, 0x66, 0x2b, 0x29, 0x3c, 0x86, 0x33, 0x54, 0x5f, 0x54, 
	0xc1, 0x81, 0x25, 0xc2, 0x70, 0x6d, 0xc7, 0xc2, 0xc4, 0x8c, 0x48, 0xfe, 0x12, 0x57, 0x74, 0xe8, 
	0x0b, 0xb8, 0xc6, 0xf2, 0xf9, 0x89, 0x8a, 0x35, 0x78, 0xbb, 0xd2, 0xda, 0x72, 0xc0, 0x82, 0x8a, 
	0x31, 0xba, 0x07, 0x83, 0x34, 0xbf, 0xe8, 0xaa, 0x8b, 0xe3, 0x06, 0xcc, 0x83, 0xc2, 0x08, 0x7f, 
	0x08, 0xa7, 0xf3, 0x38, 0x96, 0xfe, 0x8a, 0x96, 0xdc, 0x84, 0x1e, 0x53, 0xd9, 0xe9, 0x6d, 0xa4, 
	0x05, 0xfc, 0x5b, 0x1b, 0x6e, 0xcd, 0xe3, 0xd8, 0x62, 0x4b, 0x6e, 0xff, 0x75, 0x95, 0x6a, 0xfa, 
	0x4f, 0xe5, 0x7d, 0xf5, 0x68, 0x36, 0xd9, 0x1f, 0x23, 0xdc, 0xe4, 0xf1, 0x95, 0xa9, 0x61, 0x41, 
	0xed, 0x54, 0xa0, 0x9e, 0xfd, 0xe9, 0x80, 0x67, 0x8a, 0xa5, 0x0c, 0x3d, 0x00, 0xaf, 0x58, 0xe6, 
	0xa8, 0x01, 0x9f, 0x89, 0x5a, 0x09, 0xb5, 0x7d, 0x8f, 0x5b, 0xe8, 0x4b, 0x40, 0x4f, 0x89, 0x98, 
	0xc7, 0xf1, 0x53, 0x1b, 0x9a, 0x26, 0x17, 0x63, 0x53, 0xa8, 0xdd, 0x42, 0xdc, 0x42, 0x0b, 0x18, 
	0x69, 0x07, 0x2b, 0x6b, 0xa4, 0x9a, 0xee, 0xbf, 0x73, 0xb4, 0x51, 0xb8, 0x85, 0xee, 0xc3, 0x60, 
	0x11, 0xf1, 0x0d, 0xbd, 0x24, 0xec, 0xcd, 0xf2, 0x7f, 0x24, 0x2f, 0x86, 0xbb, 0x84, 0x72, 0xd2, 
	0x78, 0xf1, 0x5d, 0x8b, 0x15, 0x87, 0x33, 0x81, 0x5b, 0x6b, 0x57, 0xfd, 0xdc, 0x7e, 0xf6, 0x4f, 
	0x00, 0x00, 0x00, 0xff, 0xff, 0x54, 0x63, 0x5d, 0x65, 0xf1, 0x0a, 0x00, 0x00,
}
